#!/bin/bash
HOME_PATH=`pwd`

codecount()
{
	TYPE="."$1
	FILE=`find $HOME_PATH -name "*$TYPE"`
	CUR=0
	if [ -z "$FILE" ] ; then
		echo "not exsist *$TYPE"
	else
		CUR=`wc -l $FILE | tail -n 1 | awk '{print $1}'`
		echo "$TYPE file code lines are $CUR"
	fi
	return $CUR
}

countall ()
{
	NUM=0
	while [ $# -gt 0 ]
	do
		codecount $1
		NUM=`expr $NUM + $?`
		shift
	done
	return $NUM
}

if [ $# -gt  0 ] ; then
	countall $@
else
	countall h c cc cpp
fi

echo -e "\nall code lines are $?"
