#!/usr/bin/python
# -*- coding: utf-8 -*-

import commands
import sys

cmd="pwd"
HOME_PATH = commands.getoutput(cmd)

def code_all(*args):
	num = 0
	for arg in args:
		cmd = "find " + HOME_PATH + " -name \"*." + arg +"\""
		fp = commands.getoutput(cmd)
		cur = 0
		if fp:
			cmd = "wc -l `" + cmd + "` | tail -n 1 | awk \'{print $1}\'"
			cur = int(commands.getoutput(cmd))
			print "%s file code lines are %d" % (arg, cur)
		else:
			print "not exsist *.%s" % arg 
		num = num + cur
	return num

argc = len(sys.argv)
total = 0
if argc > 1:
	total = code_all(*sys.argv[1:])
else:
	total = code_all(*('h', 'c', 'cc', 'cpp'))

print "\nall code lines are %d" % total
